export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const REFRESHED_TOKEN = 'REFRESHED_TOKEN';
export const FORGOT_USER_PASSWORD = 'FORGOT_USER_PASSWORD';
export const RESET_USER_PASSWORD = 'RESET_USER_PASSWORD';
export const VERIFY_USER_EMAIL = 'VERIFY_USER_EMAIL';
export const GET_USER_DETAILS = 'GET_USER_DETAILS';

export const ALERT_SET = 'ALERT_SET';
export const ALERT_SET_MULTI = 'ALERT_SET_MULTI';
export const ALERT_CLEAR = 'ALERT_CLEAR';

export const INDEX_SURVEY = 'INDEX_SURVEY';
export const SHOW_SURVEY = 'SHOW_SURVEY';
export const MY_SURVEY = 'MY_SURVEY';
export const STORE_SURVEY = 'STORE_SURVEY';
export const EDIT_SURVEY = 'EDIT_SURVEY';
export const DELETE_SURVEY = 'DELETE_SURVEY';
export const TEST_SURVEY = 'TEST_SURVEY';

export const INDEX_SURVEY_QUESTION = 'INDEX_SURVEY_QUESTION';
export const SHOW_SURVEY_QUESTION = 'SHOW_SURVEY_QUESTION';
export const STORE_SURVEY_QUESTION = 'STORE_SURVEY_QUESTION';
export const EDIT_SURVEY_QUESTION = 'EDIT_SURVEY_QUESTION';
export const DELETE_SURVEY_QUESTION = 'DELETE_SURVEY_QUESTION';
export const TEST_SURVEY_QUESTION = 'TEST_SURVEY_QUESTION';

export const INDEX_USERS = 'INDEX_USERS';
export const SHOW_USER = 'SHOW_USER';

export const INDEX_COMPANIES = 'INDEX_COMPZNIES';
export const SHOW_COMPANY = 'SHOW_COMPANIES';

export const INDEX_ORDERS = 'INDEX_ORDERS';
export const SHOW_ORDER = 'SHOW_ORDER';
export const INDEX_COURIERS = 'INDEX_COURIERS';
export const SHOW_COURIER = 'SHOW_COURIER';
